"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { getWorkspaceContext, requireProjectAccess } from "@/lib/data/workspace";
import { encryptSecret } from "@/lib/security/encryption";
import { emitAuditEvent } from "@/lib/audit/events";
import { parseOtpAuthUri } from "@/lib/vault/totp";

type Result<T = undefined> = { ok: true; data?: T } | { ok: false; error: string };
const uuid = z.uuid();
const name = z.string().trim().min(1).max(120);
function encryptedColumns(value: string, prefix = "") {
  const e = encryptSecret(value);
  return prefix ? { [`${prefix}_ciphertext`]: e.ciphertext, [`${prefix}_iv`]: e.iv, [`${prefix}_auth_tag`]: e.authTag, key_version: e.keyVersion } : { ciphertext: e.ciphertext, iv: e.iv, auth_tag: e.authTag, key_version: e.keyVersion, algorithm: e.algorithm };
}
function fail(error: unknown): Result { return { ok: false, error: error instanceof Error ? error.message : "The operation could not be completed." }; }

export async function createProjectAction(input: { name: string }): Promise<Result<{ id: string }>> {
  try { const projectName=name.parse(input.name), context=await getWorkspaceContext(); if(!context)throw new Error("Workspace unavailable.");const supabase=await createClient();const base=projectName.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"project";const slug=`${base}-${crypto.randomUUID().slice(0,6)}`;const {data:project,error}=await supabase.from("projects").insert({workspace_id:context.workspaceId,owner_id:context.userId,name:projectName,slug}).select("id").single();if(error||!project)throw new Error("Project could not be created.");const {error:envError}=await supabase.from("environments").insert(["Development","Preview","Production"].map((n)=>({project_id:project.id,workspace_id:context.workspaceId,name:n,kind:n.toLowerCase()})));if(envError)throw new Error("Default environments could not be created.");await emitAuditEvent({workspaceId:context.workspaceId,actorId:context.userId,eventType:"project.created",targetType:"project",targetId:project.id,metadata:{name:projectName}});revalidatePath("/app");return{ok:true,data:{id:project.id}};}catch(e){return fail(e);}
}
export async function renameProjectAction(input:{id:string;name:string}):Promise<Result>{try{uuid.parse(input.id);const projectName=name.parse(input.name),access=await requireProjectAccess(input.id),supabase=await createClient();const{error}=await supabase.from("projects").update({name:projectName,updated_at:new Date().toISOString()}).eq("id",input.id).eq("workspace_id",access.workspaceId);if(error)throw new Error("Project could not be renamed.");await emitAuditEvent({workspaceId:access.workspaceId,actorId:access.userId,eventType:"project.renamed",targetType:"project",targetId:input.id,metadata:{name:projectName}});revalidatePath("/app/projects");return{ok:true};}catch(e){return fail(e)}}
export async function deleteProjectAction(input:{id:string}):Promise<Result>{try{uuid.parse(input.id);const access=await requireProjectAccess(input.id),supabase=await createClient();const{error}=await supabase.from("projects").delete().eq("id",input.id).eq("workspace_id",access.workspaceId);if(error)throw new Error("Project could not be deleted.");await emitAuditEvent({workspaceId:access.workspaceId,actorId:access.userId,eventType:"project.deleted",targetType:"project",targetId:input.id,metadata:{name:access.project.name}});revalidatePath("/app");return{ok:true};}catch(e){return fail(e)}}

const secretInput=z.object({projectId:z.uuid(),environmentId:z.uuid().nullable(),serviceName:z.string().trim().min(1).max(80),name:name,value:z.string().min(1).max(65536),secretType:z.string().max(40).default("api_key"),notes:z.string().max(4000).optional(),expiresAt:z.string().datetime().nullable().optional(),rotateAt:z.string().datetime().nullable().optional()});
async function resolveService(projectId:string,workspaceId:string,serviceName:string){const supabase=await createClient(),provider=serviceName.toLowerCase();const{data:existing}=await supabase.from("services").select("id").eq("project_id",projectId).ilike("name",serviceName).limit(1).maybeSingle();if(existing)return existing.id;const allowed=["github","supabase","stripe","vercel","cloudflare","openai","anthropic","resend"];const{data,error}=await supabase.from("services").insert({project_id:projectId,workspace_id:workspaceId,name:serviceName,provider:allowed.includes(provider)?provider:"custom"}).select("id").single();if(error||!data)throw new Error("Service could not be created.");return data.id;}
export async function createSecretAction(raw:z.input<typeof secretInput>):Promise<Result<{id:string}>>{try{const input=secretInput.parse(raw),access=await requireProjectAccess(input.projectId),supabase=await createClient(),serviceId=await resolveService(input.projectId,access.workspaceId,input.serviceName);if(input.environmentId){const{data:env}=await supabase.from("environments").select("id").eq("id",input.environmentId).eq("project_id",input.projectId).maybeSingle();if(!env)throw new Error("Environment not found.");}const{data,error}=await supabase.from("secrets").insert({workspace_id:access.workspaceId,owner_id:access.userId,project_id:input.projectId,environment_id:input.environmentId,service_id:serviceId,name:input.name,secret_type:input.secretType,notes:input.notes||null,expires_at:input.expiresAt||null,rotate_at:input.rotateAt||null,...encryptedColumns(input.value)}).select("id").single();if(error||!data)throw new Error("Secret could not be stored.");await emitAuditEvent({workspaceId:access.workspaceId,actorId:access.userId,eventType:"secret.created",targetType:"secret",targetId:data.id,metadata:{name:input.name,service:input.serviceName,projectId:input.projectId,environmentId:input.environmentId}});revalidatePath("/app/vault");return{ok:true,data:{id:data.id}};}catch(e){return fail(e)}}
export async function updateSecretAction(raw:{id:string;name:string;notes?:string;expiresAt?:string|null;rotateAt?:string|null;value?:string}):Promise<Result>{try{const input=z.object({id:uuid,name,notes:z.string().max(4000).optional(),expiresAt:z.string().datetime().nullable().optional(),rotateAt:z.string().datetime().nullable().optional(),value:z.string().min(1).max(65536).optional()}).parse(raw),context=await getWorkspaceContext();if(!context)throw new Error("Workspace unavailable.");const supabase=await createClient();const{data:current}=await supabase.from("secrets").select("id").eq("id",input.id).eq("workspace_id",context.workspaceId).eq("owner_id",context.userId).maybeSingle();if(!current)throw new Error("Secret not found.");const patch:Record<string,unknown>={name:input.name,notes:input.notes||null,expires_at:input.expiresAt||null,rotate_at:input.rotateAt||null,updated_at:new Date().toISOString()};if(input.value)Object.assign(patch,encryptedColumns(input.value));const{error}=await supabase.from("secrets").update(patch).eq("id",input.id).eq("owner_id",context.userId);if(error)throw new Error("Secret could not be updated.");await emitAuditEvent({workspaceId:context.workspaceId,actorId:context.userId,eventType:input.value?"secret.rotated":"secret.updated",targetType:"secret",targetId:input.id,metadata:{name:input.name}});revalidatePath("/app/vault");return{ok:true};}catch(e){return fail(e)}}
export async function deleteSecretAction(id:string):Promise<Result>{try{uuid.parse(id);const context=await getWorkspaceContext();if(!context)throw new Error("Workspace unavailable.");const supabase=await createClient();const{data}=await supabase.from("secrets").select("id,name").eq("id",id).eq("workspace_id",context.workspaceId).eq("owner_id",context.userId).maybeSingle();if(!data)throw new Error("Secret not found.");const{error}=await supabase.from("secrets").delete().eq("id",id).eq("owner_id",context.userId);if(error)throw new Error("Secret could not be deleted.");await emitAuditEvent({workspaceId:context.workspaceId,actorId:context.userId,eventType:"secret.deleted",targetType:"secret",targetId:id,metadata:{name:data.name}});revalidatePath("/app/vault");return{ok:true};}catch(e){return fail(e)}}

export async function importEnvAction(raw:{projectId:string;environmentId:string;entries:{name:string;value:string;serviceName:string}[]}):Promise<Result<{created:number;duplicates:string[]}>>{try{const input=z.object({projectId:uuid,environmentId:uuid,entries:z.array(z.object({name, value:z.string().min(1).max(65536),serviceName:z.string().min(1).max(80)})).min(1).max(200)}).parse(raw),access=await requireProjectAccess(input.projectId),supabase=await createClient();const{data:existing}=await supabase.from("secrets").select("name").eq("project_id",input.projectId).eq("environment_id",input.environmentId).in("name",input.entries.map(e=>e.name));const duplicates=(existing??[]).map(x=>x.name),selected=input.entries.filter(x=>!duplicates.includes(x.name));for(const entry of selected){const serviceId=await resolveService(input.projectId,access.workspaceId,entry.serviceName);const{error}=await supabase.from("secrets").insert({workspace_id:access.workspaceId,owner_id:access.userId,project_id:input.projectId,environment_id:input.environmentId,service_id:serviceId,name:entry.name,...encryptedColumns(entry.value)});if(error)throw new Error(`Import stopped at ${entry.name}.`);}await emitAuditEvent({workspaceId:access.workspaceId,actorId:access.userId,eventType:"secret.env_imported",targetType:"project",targetId:input.projectId,metadata:{created:selected.length,duplicates:duplicates.length,environmentId:input.environmentId}});revalidatePath("/app/vault");return{ok:true,data:{created:selected.length,duplicates}};}catch(e){return fail(e)}}

export async function addAuthenticatorAction(raw:{uri:string;issuer?:string;accountName?:string}):Promise<Result>{try{const parsed=parseOtpAuthUri(raw.uri),context=await getWorkspaceContext();if(!context)throw new Error("Workspace unavailable.");const issuer=name.parse(raw.issuer||parsed.issuer),account=name.parse(raw.accountName||parsed.label.split(":").at(-1)||parsed.label),supabase=await createClient();const{data,error}=await supabase.from("authenticator_entries").insert({workspace_id:context.workspaceId,owner_id:context.userId,issuer,account_name:account,...encryptedColumns(parsed.secret,"seed")}).select("id").single();if(error||!data)throw new Error("Authenticator could not be saved.");await emitAuditEvent({workspaceId:context.workspaceId,actorId:context.userId,eventType:"authenticator.created",targetType:"authenticator",targetId:data.id,metadata:{issuer,account}});revalidatePath("/app/vault/authenticator");return{ok:true};}catch(e){return fail(e)}}
export async function renameAuthenticatorAction(id:string,issuer:string,accountName:string):Promise<Result>{try{uuid.parse(id);const context=await getWorkspaceContext();if(!context)throw new Error("Workspace unavailable.");const supabase=await createClient();const{error}=await supabase.from("authenticator_entries").update({issuer:name.parse(issuer),account_name:name.parse(accountName),updated_at:new Date().toISOString()}).eq("id",id).eq("owner_id",context.userId);if(error)throw new Error("Authenticator could not be renamed.");await emitAuditEvent({workspaceId:context.workspaceId,actorId:context.userId,eventType:"authenticator.updated",targetType:"authenticator",targetId:id,metadata:{issuer}});revalidatePath("/app/vault/authenticator");return{ok:true};}catch(e){return fail(e)}}
export async function deleteAuthenticatorAction(id:string):Promise<Result>{try{uuid.parse(id);const context=await getWorkspaceContext();if(!context)throw new Error("Workspace unavailable.");const supabase=await createClient();const{data}=await supabase.from("authenticator_entries").delete().eq("id",id).eq("owner_id",context.userId).select("issuer").maybeSingle();if(!data)throw new Error("Authenticator not found.");await emitAuditEvent({workspaceId:context.workspaceId,actorId:context.userId,eventType:"authenticator.deleted",targetType:"authenticator",targetId:id,metadata:{issuer:data.issuer}});revalidatePath("/app/vault/authenticator");return{ok:true};}catch(e){return fail(e)}}

export async function createRecoverySetAction(raw:{service:string;accountName:string;codes:string[]}):Promise<Result>{try{const input=z.object({service:name,accountName:name,codes:z.array(z.string().trim().min(1).max(500)).min(1).max(100)}).parse(raw),context=await getWorkspaceContext();if(!context)throw new Error("Workspace unavailable.");const unique=[...new Set(input.codes)],supabase=await createClient();const{data,error}=await supabase.from("recovery_code_sets").insert({workspace_id:context.workspaceId,owner_id:context.userId,service:input.service,account_name:input.accountName,total_count:unique.length,remaining_count:unique.length,...encryptedColumns(JSON.stringify(unique),"codes")}).select("id").single();if(error||!data)throw new Error("Recovery codes could not be stored.");await emitAuditEvent({workspaceId:context.workspaceId,actorId:context.userId,eventType:"recovery.created",targetType:"recovery_set",targetId:data.id,metadata:{service:input.service,account:input.accountName,total:unique.length}});revalidatePath("/app/vault/recovery");return{ok:true};}catch(e){return fail(e)}}
export async function deleteRecoverySetAction(id:string):Promise<Result>{try{uuid.parse(id);const context=await getWorkspaceContext();if(!context)throw new Error("Workspace unavailable.");const supabase=await createClient();const{data}=await supabase.from("recovery_code_sets").delete().eq("id",id).eq("owner_id",context.userId).select("service").maybeSingle();if(!data)throw new Error("Recovery set not found.");await emitAuditEvent({workspaceId:context.workspaceId,actorId:context.userId,eventType:"recovery.deleted",targetType:"recovery_set",targetId:id,metadata:{service:data.service}});revalidatePath("/app/vault/recovery");return{ok:true};}catch(e){return fail(e)}}
export async function completeOnboardingAction():Promise<Result>{try{const context=await getWorkspaceContext();if(!context)throw new Error("Workspace unavailable.");const supabase=await createClient();const{error}=await supabase.from("user_preferences").upsert({user_id:context.userId,onboarding_completed_at:new Date().toISOString(),updated_at:new Date().toISOString()});if(error)throw new Error("Onboarding could not be saved.");revalidatePath("/app");return{ok:true};}catch(e){return fail(e)}}
