-- Candler product reset. Apply after reviewing in a Supabase preview branch.
create extension if not exists pgcrypto;

create type public.workspace_role as enum ('owner','admin','member');
create type public.environment_kind as enum ('development','preview','production','custom');
create type public.agent_action_status as enum ('proposed','awaiting_approval','running','verified','failed');
create type public.cloud_file_status as enum ('uploading','verifying','backed_up','failed');

create table public.workspaces (id uuid primary key default gen_random_uuid(), name text not null, owner_id uuid not null references auth.users on delete cascade, created_at timestamptz not null default now());
create table public.workspace_members (workspace_id uuid references public.workspaces on delete cascade, user_id uuid references auth.users on delete cascade, role public.workspace_role not null default 'member', created_at timestamptz not null default now(), primary key(workspace_id,user_id));
create table public.projects (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, owner_id uuid not null references auth.users on delete cascade, name text not null, slug text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,slug));
create table public.environments (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, workspace_id uuid not null references public.workspaces on delete cascade, name text not null, kind public.environment_kind not null, created_at timestamptz not null default now(), unique(project_id,name));
create table public.services (id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects on delete cascade, workspace_id uuid not null references public.workspaces on delete cascade, name text not null, provider text not null check(provider in ('github','supabase','stripe','vercel','cloudflare','openai','anthropic','resend','custom')), created_at timestamptz not null default now());

-- No plaintext value column exists. The key lives in server runtime/KMS only.
create table public.secrets (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, project_id uuid references public.projects on delete cascade, environment_id uuid references public.environments on delete set null, service_id uuid references public.services on delete set null, owner_id uuid not null references auth.users on delete cascade, name text not null, ciphertext text not null, iv text not null, auth_tag text not null, key_version smallint not null default 1, algorithm text not null default 'aes-256-gcm' check(algorithm='aes-256-gcm'), secret_type text not null default 'api_key', notes text, tags text[] not null default '{}', expires_at timestamptz, rotate_at timestamptz, last_accessed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.authenticator_entries (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, owner_id uuid not null references auth.users on delete cascade, issuer text not null, account_name text not null, seed_ciphertext text not null, seed_iv text not null, seed_auth_tag text not null, key_version smallint not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.recovery_code_sets (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, owner_id uuid not null references auth.users on delete cascade, service text not null, account_name text not null, codes_ciphertext text not null, codes_iv text not null, codes_auth_tag text not null, key_version smallint not null default 1, remaining_count integer not null check(remaining_count>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.cloud_folders (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, project_id uuid references public.projects on delete set null, parent_id uuid references public.cloud_folders on delete cascade, owner_id uuid not null references auth.users on delete cascade, name text not null, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.cloud_files (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, project_id uuid references public.projects on delete set null, folder_id uuid references public.cloud_folders on delete set null, owner_id uuid not null references auth.users on delete cascade, original_filename text not null, object_key text not null unique, mime_type text not null, size_bytes bigint not null check(size_bytes>=0), checksum_sha256 text, status public.cloud_file_status not null default 'uploading', storage_tier text not null default 'standard', deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table public.agent_conversations (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, project_id uuid references public.projects on delete set null, owner_id uuid not null references auth.users on delete cascade, title text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.agent_actions (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.agent_conversations on delete cascade, workspace_id uuid not null references public.workspaces on delete cascade, owner_id uuid not null references auth.users on delete cascade, action_type text not null, safe_input jsonb not null default '{}', status public.agent_action_status not null default 'proposed', approved_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now());
create table public.audit_events (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, actor_id uuid references auth.users on delete set null, event_type text not null, target_type text not null, target_id uuid, metadata jsonb not null default '{}', ip_hash text, created_at timestamptz not null default now());
create table public.subscriptions (id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces on delete cascade, owner_id uuid not null references auth.users on delete cascade, stripe_customer_id text not null, stripe_subscription_id text unique, product_key text not null, status text not null, current_period_end timestamptz, storage_quota_bytes bigint not null default 10737418240, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create or replace function public.is_workspace_member(target uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.workspace_members wm where wm.workspace_id=target and wm.user_id=auth.uid()) or exists(select 1 from public.workspaces w where w.id=target and w.owner_id=auth.uid()) $$;
revoke all on function public.is_workspace_member(uuid) from public; grant execute on function public.is_workspace_member(uuid) to authenticated;

alter table public.workspaces enable row level security; alter table public.workspace_members enable row level security; alter table public.projects enable row level security; alter table public.environments enable row level security; alter table public.services enable row level security; alter table public.secrets enable row level security; alter table public.authenticator_entries enable row level security; alter table public.recovery_code_sets enable row level security; alter table public.cloud_folders enable row level security; alter table public.cloud_files enable row level security; alter table public.agent_conversations enable row level security; alter table public.agent_actions enable row level security; alter table public.audit_events enable row level security; alter table public.subscriptions enable row level security;

create policy workspace_access on public.workspaces for all to authenticated using(public.is_workspace_member(id)) with check(owner_id=auth.uid());
create policy membership_access on public.workspace_members for select to authenticated using(public.is_workspace_member(workspace_id));
create policy membership_owner_write on public.workspace_members for all to authenticated using(exists(select 1 from public.workspaces w where w.id=workspace_id and w.owner_id=auth.uid())) with check(exists(select 1 from public.workspaces w where w.id=workspace_id and w.owner_id=auth.uid()));
create policy project_access on public.projects for all to authenticated using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id) and owner_id=auth.uid());
create policy environment_access on public.environments for all to authenticated using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy service_access on public.services for all to authenticated using(public.is_workspace_member(workspace_id)) with check(public.is_workspace_member(workspace_id));
create policy secret_access on public.secrets for all to authenticated using(public.is_workspace_member(workspace_id) and owner_id=auth.uid()) with check(public.is_workspace_member(workspace_id) and owner_id=auth.uid());
create policy authenticator_access on public.authenticator_entries for all to authenticated using(public.is_workspace_member(workspace_id) and owner_id=auth.uid()) with check(public.is_workspace_member(workspace_id) and owner_id=auth.uid());
create policy recovery_access on public.recovery_code_sets for all to authenticated using(public.is_workspace_member(workspace_id) and owner_id=auth.uid()) with check(public.is_workspace_member(workspace_id) and owner_id=auth.uid());
create policy folder_access on public.cloud_folders for all to authenticated using(public.is_workspace_member(workspace_id) and owner_id=auth.uid()) with check(public.is_workspace_member(workspace_id) and owner_id=auth.uid());
create policy file_access on public.cloud_files for all to authenticated using(public.is_workspace_member(workspace_id) and owner_id=auth.uid()) with check(public.is_workspace_member(workspace_id) and owner_id=auth.uid());
create policy conversation_access on public.agent_conversations for all to authenticated using(public.is_workspace_member(workspace_id) and owner_id=auth.uid()) with check(public.is_workspace_member(workspace_id) and owner_id=auth.uid());
create policy action_access on public.agent_actions for all to authenticated using(public.is_workspace_member(workspace_id) and owner_id=auth.uid()) with check(public.is_workspace_member(workspace_id) and owner_id=auth.uid());
create policy audit_read on public.audit_events for select to authenticated using(public.is_workspace_member(workspace_id));
create policy subscription_read on public.subscriptions for select to authenticated using(public.is_workspace_member(workspace_id) and owner_id=auth.uid());
-- Audit writes and subscription mutations are server-only through the service role.

create index secrets_workspace_project_idx on public.secrets(workspace_id,project_id); create index cloud_files_workspace_deleted_idx on public.cloud_files(workspace_id,deleted_at); create index cloud_files_search_idx on public.cloud_files using gin(to_tsvector('simple',original_filename)); create index audit_events_workspace_created_idx on public.audit_events(workspace_id,created_at desc); create index agent_conversations_workspace_idx on public.agent_conversations(workspace_id,updated_at desc);
